name: publish
on:
  push:
    branches: ['sc2-next-mirror']
  workflow_dispatch: {}
jobs:
  publish:
    name: publish package
    runs-on: ubuntu-latest
    steps:
      # - copy code below to release.yml -
      - uses: actions/checkout@v4
      - name: Install base dependencies
        run: |
          sudo apt update
          sudo apt -y install smpq parallel
      - name: Build
        run: |
          ./build_release_package.sh
      - name: zip
        run: |
          pushd target
          zip -r ../sc2-data.zip .
          popd
      - name: Deploy
        uses: WebFreak001/deploy-nightly@v3.1.0
        with:
          # find out this value by opening https://api.github.com/repos/<owner>/<repo>/releases in your browser and copy the full "upload_url" value including the {?name,label} part
          upload_url: https://uploads.github.com/repos/MatthewMarinets/Archipelago-SC2-data/releases/165275072/assets{?name,label}
          release_id: 165275072
          asset_path: ./sc2-data.zip
          asset_name: Archipelago-SC2Data
          asset_content_type: application/zip
          # A file, directory or wildcard pattern that describes what to upload
          # Required.
          retention-days: 7
